# Server configuration
# TODO : set using api gateway
server:
    port: 8081

spring:
    application:
        name: user-service
    datasource:
        url: jdbc:postgresql://localhost:5432/durin_user_service_db
        username: postgres
        password: pkp245464
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    # Uncomment below if you want formatted SQL logs
    # properties:
    #   hibernate:
    #     format_sql: true

# Logging configuration
logging:
    level:
        root: INFO
        org.springframework.security: DEBUG
        org.hibernate: ERROR
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36}: %msg%n"