server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/durin's-misty-melody/user-service/**

        - id: music-service
          uri: http://localhost:8082
          predicates:
            - Path=/durin's-misty-melody/music-service/**
