server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/durin's-misty-melody/user-service/**

        - id: music-service
          uri: http://localhost:8082
          predicates:
            - Path=/durin's-misty-melody/music-service/**

        - id: playlist-service
          uri: http://localhost:8083
          predicates:
            - Path=/durin's-misty-melody/playlist-service/**

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/durin's-misty-melody/notification-service/**

        - id: analytics-service
          uri: http://localhost:8085
          predicates:
              - Path=/durin's-misty-melody/analytics-service/**

        - id: search-service
          uri: http://localhost:8086
          predicates:
              - Path=/durin's-misty-melody/search-service/**