# TODO : set using api gateway

server:
  port: 8082

spring:
  application:
    name: music-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/musicservicedb
      database: musicservicedb

