server:
  port: 8082

spring:
  application:
    name: music-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/musicservicedb
      database: musicservicedb

  datasource:
    url: jdbc:postgresql://localhost:5432/uploadservicedb
    username: postgres
    password: pkp245464
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  # Uncomment below if you want formatted SQL logs
  # properties:
  #   hibernate:
  #     format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


aws:
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}
  bucket:
    name: ${BUCKET_NAME}
